adding executions inside container on pre-commit
kiwfy/ala-microservice pull request #15
Opened 2022-08-23 19:25 UTC by tavaresmatheus

Checking if the container name is the default to the project, and if everything is ok, then execute every process inside the container.

2022-08-23 21:14 UTC, espositovitor approved these changes

2022-08-23 21:27 UTC, JhonatanEstabile approved these changes

2022-08-24 21:07 UTC, espositovitor requested changes
O lint não esta funcionando

2022-09-25 20:03 UTC, espositovitor approved these changes

2022-09-25 20:03 UTC, merged