Feature to use whereIn and Between filters in list routes
kiwfy/ala-microservice pull request #17
Opened 2023-03-06 12:57 UTC by jpmgoncalves12

2023-03-06 12:59 UTC, dayknightmare approved these changes

2023-03-06 13:02 UTC, JhonatanEstabile approved these changes

2023-03-06 13:07 UTC, espositovitor requested changes

2023-03-06 13:07 UTC, espositovitor commented on app/Repositories/BaseRepository.php
> +    }
Aqui não faltou retornar a variável **$list**? Como não esta sendo passada por referência e recebida de volta, acredito que não esta aplicando esse filtro corretamente.

2023-03-06 20:39 UTC, Creaper001 approved these changes

2023-08-29 21:28 UTC, samueldasilvadev approved these changes
LGTM!

2023-08-30 11:16 UTC, espositovitor approved these changes

2023-08-30 11:16 UTC, merged